backend:
  name: git-gateway
  branch: main

media_folder: "photos/{{slug}}"
public_folder: "/photos/{{slug}}"

collections:
  - name: "photos"
    label: "QR Photos"
    folder: "content/photos"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image 1", name: "image1", widget: "image"}
      - {label: "Image 2", name: "image2", widget: "image"}
