backend:
  name: git-gateway
  branch: main
  auth_endpoint: "/.netlify/functions/auth"

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "photos"
    label: "Photos"
    folder: "content/photos"
    create: true
    extension: "json"
    format: "json"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image1", label: "Image 1", widget: "image" }
      - { name: "image2", label: "Image 2", widget: "image" }
